export const STRINGS = {
  bigMoveIsNear: "Your big move is near.",
  continue: "Continue",
  description: "Where can you move to?",
  footer:
    "These recommendations are based on current immigration policies and your provided information.",
  getStarted: "Get Started",
  globalOpportunitiesDescription:
    "Based on your profile, we have analyzed visa options across multiple countries. These recommendations are ranked by your eligibility, with your best matches first.",
  globalOpportunitiesTitle: "Your Global Opportunities",
  likelihood: "Likelihood",
  loadingAnalyzingProfile: 'Analyzing your profile...',
  loadingCheckingCanada: 'Checking Canadian immigration pathways...',
  loadingEvaluatingGlobal: 'Evaluating global opportunities...',
  loadingCalculatingProbabilities: 'Calculating success probabilities...',
  loadingGeneratingRecommendations: 'Generating personalized recommendations...',
  loadingCreatingStrategy: 'Creating your migration strategy...',
  loadingAssessingSkills: 'Assessing your skills and qualifications...',
  loadingMatchingPrograms: 'Matching you with immigration programs...',
  loadingReviewingEducation: 'Reviewing educational background...',
  loadingAnalyzingExperience: 'Analyzing work experience...',
  loadingCheckingEligibility: 'Checking eligibility criteria...',
  loadingResearchingOptions: 'Researching visa options...',
  loadingPreparingTimeline: 'Preparing immigration timeline...',
  loadingOptimizingPath: 'Optimizing your immigration path...',
  match: "Match",
  next: "Next",
  nextSteps: "Next Steps",
  noOptionFound: "No option found.",
  of: "of",
  previous: "Previous",
  proTipTitle: "Pro tip: ",
  proTip:
    "Each country may offer multiple visa pathways. Click on different visa types to compare requirements and find your best option.",
  search: "Search",
  showLess: "Show less",
  showMore: "Show more",
  step: "Step",
  submit: "Submit",
  takeAFewMoments: "This may take a few moments...",
  question: "Question",
};

